[package]
name = "bevy_tic_tac_toe"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy-web-resizer = "4.0.1"

[dependencies.bevy]
version = "0.15.1"
default-features = false
features = [
    "bevy_asset",
    "bevy_winit",
    "bevy_render",
    "bevy_text",
    "bevy_ui",
]